<a href="https://colab.research.google.com/github/0jayer/Autonomous_Robot_Simulations/blob/main/Hw4ques1calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [ ]:
def correlation(img,F):
    #get image and filter size
    m,n= img.shape #shape returns dimesnions of array
    k,l= F.shape
    #padding image
    #using np.pad to shorten the code
    img_padded = np.pad(img,((1,1),(1,1)), mode='constant', constant_values=0)

    #converting the filter matrix into a column vector
    f = F.flatten()
    G = np.zeros((m,n))
    for i in range(m):
      for j in range(n):
        t = img_padded[i:i+k,j:j+l]  #getting the specific part of the padded image for dot product
        t_ij = t.flatten()    #converting it into column vector

        G[i,j] = np.dot(f,t_ij) #calculating the output matrix using dot product

    G_pad = np.pad(G,((1,1),(1,1)), mode='constant', constant_values=0)
    return G

In [ ]:
F1 = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])  # No change
F2 = np.array([[1,0,0],[0,0,0],[0,0,0]])          # move image down right
F3 = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])       # vertical edge detection
F4 = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])       # horizontal edge detection
F5 = np.array([[1,2,1],[2,4,2],[1,2,1]])/16       # gaussian filter
F6 = np.array([[1,1,1],[1,1,1],[1,1,1]])/9        # moving average filter

I = np.array([[7, 4, 1], [8, 5, 2], [9, 6, 3]])

G1 = correlation(I,F1)
G2 = correlation(I,F2)
G3 = correlation(I,F3)
G4 = correlation(I,F4)
G5 = correlation(I,F5)
G6 = correlation(I,F6)

print(G1)
print(G2)
print(G3)
print(G4)
print(G5)
print(G6)

[[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]
[[0. 0. 0.]
 [0. 7. 4.]
 [0. 8. 5.]]
[[-13. -15.  -7.]
 [ -4.  -6.  -4.]
 [ 13.  15.   7.]]
[[  9. -12.  -9.]
 [ 15. -18. -15.]
 [ 11. -12. -11.]]
[[3.5625 3.25   1.3125]
 [5.25   5.     2.25  ]
 [4.3125 4.25   2.0625]]
[[2.66666667 3.         1.33333333]
 [4.33333333 5.         2.33333333]
 [3.11111111 3.66666667 1.77777778]]
